import React from "react";
import { stringifyJsonLd } from "@/lib/schema";

interface JsonLdProps {
  /**
   * The JSON-LD data object to render. Can be any Schema.org type
   * generated by the schema utilities (PersonSchema, BlogPostingSchema, etc.)
   * or a custom JSON-LD object.
   */
  data: Record<string, unknown>;
  /**
   * Optional id attribute for the script tag. Useful for debugging
   * or if you need to reference the script element.
   */
  id?: string;
}

/**
 * Renders a JSON-LD structured data script tag.
 *
 * This component safely embeds Schema.org structured data into the page's <head>
 * for SEO purposes. The data is serialized using `stringifyJsonLd` which escapes
 * dangerous characters to prevent XSS attacks.
 *
 * @example
 * ```tsx
 * import { generatePersonSchema } from '@/lib/schema';
 * import { JsonLd } from '@/components/JsonLd';
 *
 * const personData = generatePersonSchema({
 *   name: 'Jordan Lang',
 *   jobTitle: 'Software Developer',
 *   url: 'https://jordanlang.dev',
 * });
 *
 * export default function Page() {
 *   return (
 *     <>
 *       <JsonLd data={personData} />
 *       <main>...</main>
 *     </>
 *   );
 * }
 * ```
 *
 * @see https://schema.org
 * @see https://developers.google.com/search/docs/appearance/structured-data
 */
export function JsonLd({ data, id }: JsonLdProps) {
  // Safely serialize the JSON-LD data with XSS protection
  const jsonLdString = stringifyJsonLd(data);

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: jsonLdString }}
      {...(id && { id })}
    />
  );
}
